#!/bin/bash

path=/tmp/bing-wallpaper.jpg

wget "http://www.bing.com/HPImageArchive.aspx?format=rss&idx=0&n=1&mkt=en-US" -O  /tmp/bing.txt
img_result=$(grep -o 'src="[^"]*"' /tmp/bing.txt | grep -o '/.*.jpg')
rm /tmp/bing.txt

curl -o $path "http://www.bing.com"$img_result
	
gsettings set org.gnome.desktop.background draw-background false
gsettings set org.gnome.desktop.background picture-uri file://$path
gsettings set org.gnome.desktop.background draw-background true

